### PR TITLE
Feature/docker compose

### PR DESCRIPTION
**Pull request by raghunadhpokkalath**

### CODE REVIEW

**Review by afaryy — APPROVED** [review]

**Review by afaryy — DISMISSED** [review]

**Review by afaryy — COMMENTED** [review]
???

Run make plan
docker-compose run --rm shell make _plan
Couldn't find env file: /home/runner/work/2020-jun-project1-externals/2020-jun-project1-externals/.env
make: *** [plan] Error 1
Makefile:12: recipe for target 'plan' failed
##[error]Process completed with exit code 2.

**Comment by raghunadhpokkalath** [comment]
Thanks @afaryy I am still working wanted to see if ci is was working with the new changes

**Review by afaryy — DISMISSED** [review]
Well done.

**Review by afaryy — APPROVED** [review]
Great!

**Pull request merged**
